# This cloudbuild script builds docker images we expect users to
# commonly deploy, and stores these in cloud registry.
# This builds the images multi-arch so they run on x64 and Raspberry Pi.
timeout: 3600s
options:
  machineType: N1_HIGHCPU_8
  volumes:
  - name: go-modules
    path: /go
  env:
  - GO111MODULE=on
  - GOPROXY=https://proxy.golang.org
  - PROJECT_ROOT=github.com/google/trillian-examples
  - GOPATH=/go
  - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore # Temporary work-around v1.proto already registered error.
  - 'DOCKER_CLI_EXPERIMENTAL=enabled'

steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['run', '--privileged', 'linuxkit/binfmt:v0.8']
    id: 'initialize-qemu'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'create', '--name', 'mybuilder']
    id: 'create-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'use', 'mybuilder']
    id: 'select-builder'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
    id: 'show-target-build-platforms'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/witness:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/witness:latest',
      '-f', './witness/golang/cmd/witness/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-witness-image'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/sumdb-feeder:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/sumdb-feeder:latest',
      '-f', './sumdbaudit/witness/cmd/feeder/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-sumdb-feeder-image'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/distribute-to-github:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/distribute-to-github:latest',
      '-f', './serverless/cmd/distribute/github/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-distribute-to-github-image'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/serverless-feeder:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/serverless-feeder:latest',
      '-f', './serverless/cmd/feeder/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-serverless-feeder-image'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/rekor-feeder:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/rekor-feeder:latest',
      '-f', './feeder/cmd/rekor_feeder/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-rekor-feeder-image'
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'buildx',
      'build',
      '--platform', '$_DOCKER_BUILDX_PLATFORMS',
      '-t', 'gcr.io/$PROJECT_ID/pixel-bt-feeder:latest',
      '--cache-from', 'gcr.io/$PROJECT_ID/pixel-bt-feeder:latest',
      '-f', './feeder/cmd/pixel_bt_feeder/Dockerfile',
      '--push',
      '.'
    ]
    waitFor:
      - show-target-build-platforms
    id: 'build-pixel-feeder-image'

  # Write this build to a serverless log. Note this step is experimental, and it is configured to
  # always appear to succeed from the view of Cloud Build.
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      # Set ERR trap to be inherited by shell functions. Allows our bash command logs to show up in
      # Cloud Console.
      - '-E'
      - '-c'
      - |
      - >-
        gcloud functions call create_gcs_object --data='{
          "bucket":"tlog",
          "entryContent":"${REPO_NAME},${COMMIT_SHA},linux/amd64",
          "entryPath":"${REPO_NAME}-linux-amd64"
        }' &&
        gcloud functions call create_gcs_object --data='{
          "bucket":"tlog",
          "entryContent":"${REPO_NAME},${COMMIT_SHA},linux/arm/v7",
          "entryPath":"${REPO_NAME}-linux-arm-v7"
        }' || exit 0
      # `exit 0` will tell Cloud Build that this step succeeded. See workaround documented here:
      # https://github.com/GoogleCloudPlatform/cloud-builders/issues/253#issuecomment-381600420
      # TODO(jayhou): also invoke the `sequence` and `integrate` functions of the log.

substitutions:
  _DOCKER_BUILDX_PLATFORMS: 'linux/amd64,linux/arm/v7'
